### ISSUE TITLE
Incorrect order of injection methods in cascading ifs

### ISSUE THREAD

**Issue by bryant1410** [tbroyer/bullet#7] opened 2016-03-08 13:03 UTC
I see that the order of the members-injection methods in the cascading ifs is not right. I'm using SNAPSHOT in [the demo branch of our Android base project](https://github.com/xmartlabs/Android-Base-Project/tree/demo). For instance, `StartActivity` is after `BaseActivity`, but it should be before.

**Comment by tbroyer** [comment] 2016-03-08 17:20
I must say it doesn't really surprises me. Getting it right is not easy given the constraints (of lack of):

 - JSR-330 says injectable methods must be non-abstract; I was about to change the implementation to loop over `getClass().getSuperclass()`, ignoring interfaces, but actually you can have Java 8 `default` methods, and Dagger‡ will invoke them! (I.e. given a `void inject(I i)` on a Dagger‡ `@Component`, `interface I { @Inject default void setFoo(Foo foo) { … }` and `class A implements I { /* does NOT override setFoo */ }`, and no members-injection method for `A`; when calling `inject()` with an instance of `A` as argument, `I`'s `setFoo` will be invoked)
 - “sorting” a hierarchy taking interfaces into account is not that easy (probably not that hard either). The current implementation in `master` is admittedly broken (though slightly less broken than in 0.20). We could possibly make it better by removing the sort on names (which is what I believe is breaking your use-case), but that wouldn't be a complete fix (imagine `A implements I`, `C`, `B implements I2`, `I2 extends I`: `C` would compare equal to `A`, `B`, `I2` and `I`, but `A` would compare lesser than `I` and equal to `B`, and `B` would be lesser than `I2` which is lesser than `I`; depending on the order of the inputs, the outputs would still be sorted differently).

The difficulty here is to somehow apply [the JLS rules for selecting an appropriate method overload](https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.12.2) (except that our methods here aren't necessarily overloads: they can have different names) at runtime (similar to `invokedynamic` or `java.lang.invoke`, but without using them).
Also, if you have `void inject(I i)` and `void anotherInject(I2 i)` where `I` and `I2` are two independent interfaces, and you call Bullet• with a class that implements both interfaces, what should happen?

In your case, as a workaround, you can try reordering your component methods to influence the sorting of the methods in the processor.

Pull-requests welcome, but as I already told you, you'd better refactor to avoid the need for Bullet• altogether.

**Comment by bryant1410** [comment] 2016-03-09 16:03
Ok. I will try to refactor my code.

By the way, regarding this: how can I debug an annotation processor? I tried putting a breakpoint in the Processor file and turning on the remote debugging, while doing a clean-and-generate with gradle, but didn't work.

**Comment by tbroyer** [comment] 2016-03-09 16:59
You need to debug the Gradle process: add your `-agentlib:…` stanza to `GRADLE_OPTS` or `org.gradle.jvmargs` property (e.g. in your `gradle.properties`). The former requires you to **not** use the Gradle Daemon (`./gradlew --no-daemon assemble`), which is probably a good idea anyway when debugging.
Apparently, you could also use `./gradlew --no-daemon -Dorg.gradle.debug=true assemble`; see https://discuss.gradle.org/t/how-do-you-attach-a-debugger-to-gradle-so-that-i-can-debug-it-running-a-task/7526

Alternatively, if you can, write a test using compile-testing and simply debug the test ;-)

**Comment by bryant1410** [comment] 2016-03-09 17:52
Thanks for the help man!

**Comment by bryant1410** [comment] 2016-03-10 12:40
What is the problem about the non-unique output if we remove the sort on names? In your example, all outputs will be valid (A B C I2 I and B I2 A I C are valid as cascading ifs).

**Comment by tbroyer** [comment] 2016-03-10 13:03
IIRC, when I tried it with your repo it didn't solve the issue. The problem is that `A` is "smaller" than `I` and equal to `C`, and `I` is equal to `C`; depending on the sorting algorithm, **and** the order of the inputs, it wouldn't surprise me if it could end up being sorted as `I`, `C`, `A` (because `I == C` and `C == A`), which would be wrong (because `A < I`).
I don't think the proper sorting can be achieve using a `java.util.Comparator` because we don't have a _total order_ for the things we're comparing (`A` is not actually _equal_ to `C` just like `I` is not _equal_ to `C` either). A better approach might be to build a graph of the dependencies between inputs and then _walk_ the graph (and making sure `I` comes after `A` even if `B` and `I2` are visited first).

**Comment by bryant1410** [comment] 2016-03-10 13:10
Oh, I see, you're right.

**Comment by tbroyer** [comment] 2016-03-13 02:41
Should hopefully be fixed by e5044b53dfb278ac07bf56585ae27b69ae1bd948

**Closed by tbroyer** 2016-03-13 02:41 UTC

**Comment by tbroyer** [comment] 2016-03-13 16:45
I'll cut a release as soon as you report it's actually fixed for you; unless you think there might be bugs (even if you haven't faced them), and/or you think it should be re-implemented differently (though that could be done for a subsequent release).

**Comment by bryant1410** [comment] 2016-03-14 12:33
This is working with e5044b5. You can release if you want. However, I think the implementation could be more efficient. Right now is Ω(n^2), so it will make slow builds in projects with high quantity of injected methods (which is although not so common, I think). This problem is about finding a Topological Sort in a Graph, so the problem can be canned and delegated to a graph library to be solved efficiently, as in 170bdb2. I strongly think something like this should be followed.

This implementation first add the injected types to the graph, and its parents, while saving missing edges because parents are not in the graph. Then it starts to add the missing parents and its missing ancestors too, with the missing edges.

The change is somehow fast to do, so a release could be done with all together. But you can release meanwhile if you prefer it.

BTW, there is now a great way to test the implementation!
